rootProject.name = 'SiteInspectionApp'

def rnSettingsFile = file("../node_modules/@react-native/gradle-plugin/settings.gradle")
if (rnSettingsFile.exists()) {
    apply from: rnSettingsFile
}

def rnGradlePlugin = file("../node_modules/@react-native/gradle-plugin")
if (rnGradlePlugin.exists()) {
    includeBuild(rnGradlePlugin)
}

include ':app'

def reactNativeGradlePlugin = file("../node_modules/react-native-gradle-plugin")
if (reactNativeGradlePlugin.exists()) {
    includeBuild(reactNativeGradlePlugin)
}
